#!/bin/bash

# Deploy Frontend to AWS ECS using GitHub Actions
echo "🚀 Deployment Instructions for AWS ECS"
echo "====================================="
echo ""
echo "To deploy the frontend to AWS, follow these steps:"
echo ""
echo "1. Open your browser and navigate to:"
echo "   https://github.com/kodingGeek/sabpaisa-tokenization-frontend/actions/workflows/ecs-deploy.yml"
echo ""
echo "2. Click the 'Run workflow' button"
echo ""
echo "3. Select the following options:"
echo "   - Branch: master (default)"
echo "   - Target Environment: dev (default)"
echo "   - Docker Image Tag: latest (or leave default)"
echo "   - Backend API URL: auto-detect (default)"
echo ""
echo "4. Click 'Run workflow'"
echo ""
echo "The deployment will:"
echo "✓ Build Docker image with fixed TypeScript issues"
echo "✓ Push to AWS ECR"
echo "✓ Deploy to ECS Fargate"
echo "✓ Run health checks"
echo "✓ Provide deployment URLs"
echo ""
echo "Monitor the deployment progress in the Actions tab."
echo ""
echo "📝 Note: Make sure you have AWS credentials configured in GitHub Secrets:"
echo "   - AWS_ACCESS_KEY_ID"
echo "   - AWS_SECRET_ACCESS_KEY"
echo ""